### ISSUE TITLE
Any way to get rid of this crash code at the end?

### ISSUE THREAD

**Issue by Kezzsim** [SolidHal/spotify-ripper#10]
So the good news is this script works just fine for most of the stuff I do, I don't have a particular need to remove things from my playlists after ripping them so I originally intended to leave that feature alone... But every time I try to rip something I always get this same error:

`Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 366, in run
    self.post.remove_tracks_from_playlist()
  File "/Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/post_actions.py", line 287, in remove_tracks_from_playlist
    remove_all_from_playlist(ripper.session.user.canonical_name, ripper.playlist_uri)
  File "/Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/remove_all_from_playlist.py", line 19, in remove_all_from_playlist
    tracks = get_playlist_tracks(username, playlistURI)
  File "/Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/remove_all_from_playlist.py", line 31, in get_playlist_tracks
    p1, p2, p3, p4, rPlaylistID = playlistURI.split(':', 5)
AttributeError: 'NoneType' object has no attribute 'split'`

What does that mean exactly? Since then I've tried following your webAPI tutorial for setting up the feature that this links to anyway (remove_all_from_playlist) but there's been no changed result. 

If nothing else I'd just like to hide the error since it isn't actually effecting anything.

-Cheers

**Comment by SolidHal** [comment]
It looks like it calls remove_tracks_from_playlist() even if the flag isn't specified for some reason. I may get around to fixing this at some point, but since I don't have the time at the moment and it doesn't really affect functionality (yes, I know, crashing to exit is bad) it'll be awhile.
