### ISSUE TITLE
Python errors

### ISSUE THREAD

**Issue by kingbu** [SolidHal/spotify-ripper#27]
Hi, 

anyone here could help me won these errors?
I cannot understand why suddenly this script stopped working for me. 
Here below what is happening. 

Thanks a lot for Your kind help ;-)

Spotify Ripper - v2.10.5
  Encoding output:      FLAC, Compression Level: 8
  Spotify bitrate:      320 kbps
  Unicode support:      Yes
  Output directory:     /home/bu/Music
  Settings directory:   /home/bu/.spotify-ripper
  Format String:        {album_artist}/{album}/{artist} - {track_name}.{ext}
  Overwrite files:      No
Logging in...
Logged in as ############
Traceback (most recent call last):
  File "/usr/bin/spotify-ripper", line 11, in <module>
    load_entry_point('spotify-ripper==2.10.5', 'console_scripts', 'spotify-ripper')()
  File "/usr/lib64/python3.4/site-packages/spotify_ripper-2.10.5-py3.4.egg/EGG-INFO/scripts/main.py", line 594, in main
    stdin_settings = termios.tcgetattr(sys.stdin)
termios.error: (25, 'Inappropriate ioctl for device')
Logging out...

**Comment by tcurdt** [comment]
Did you work this out in the end?
