### ISSUE TITLE
Segfault: AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by Huskion** [SolidHal/spotify-ripper#30]
Hello, on the off chance that someone is still looking at this. I get this with every attempt to use spotify-ripper; the song downloads but corrupted, the file seems incomplete and there are no ID3 tags or album art. Any ideas?

```
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/marty/.local/lib/python3.6/site-packages/spotify_ripper/ripper.py", line 366, in run
    self.post.remove_tracks_from_playlist()
  File "/home/marty/.local/lib/python3.6/site-packages/spotify_ripper/post_actions.py", line 287, in remove_tracks_from_playlist
    remove_all_from_playlist(ripper.session.user.canonical_name, ripper.playlist_uri)
  File "/home/marty/.local/lib/python3.6/site-packages/spotify_ripper/remove_all_from_playlist.py", line 19, in remove_all_from_playlist
    tracks = get_playlist_tracks(username, playlistURI)
  File "/home/marty/.local/lib/python3.6/site-packages/spotify_ripper/remove_all_from_playlist.py", line 31, in get_playlist_tracks
    p1, p2, p3, p4, rPlaylistID = playlistURI.split(':', 5)
AttributeError: 'NoneType' object has no attribute 'split'

Segmentation fault
```

**Comment by tjmurray** [comment]
Can't help with this error, but I just posted in another thread to say this this fork:
https://github.com/wolfmanx/spotify-ripper/tree/pr-collect

works perfectly (I've been using it for the last year). So if you just need to quickly get a ripper working then you can use that for now!

**Comment by Huskion** [comment]
I'm afraid I can't seem to get that going using pip3;

```
~$ pip3 install pip3 install git+https://github.com/wolfmanx/spotify-ripper/tree/pr-collect --upgrade
Collecting git+https://github.com/wolfmanx/spotify-ripper/tree/pr-collect
  Cloning https://github.com/wolfmanx/spotify-ripper/tree/pr-collect to /tmp/pip-nwb1gko1-build
fatal: repository 'https://github.com/wolfmanx/spotify-ripper/tree/pr-collect/' not found
Command "git clone -q https://github.com/wolfmanx/spotify-ripper/tree/pr-collect /tmp/pip-nwb1gko1-build" failed with error code 128 in None
```

**Comment by Alan111S** [comment]
Drop the /tree/pr-collect part and it'll work ;)

**Comment by tjmurray** [comment]
No don't drop the pr-collect part since this is the branch you want to be using. I'm not sure what pip3 is, but I believe the way you're specifying the branch is wrong. I used the following which worked fine:

pip install git+https://github.com/wolfmanx/spotify-ripper.git@pr-collect

**Comment by Alan111S** [comment]
Aaah, OK - thanks for the heads up

**Comment by Huskion** [comment]
The errors are gone, but it just segfaults right away. I think I might have broken something regarding dependencies or my python interpreter, and reinstalling everything doesn't seem to work. I'm stumped.
