### ISSUE TITLE
Downloading podcast (whole show or episode)

### ISSUE THREAD

**Issue by bornox** [SolidHal/spotify-ripper#31]
Is there any way to download whole podcasts? Or episodes?

URI code looks like: 
spotify:show:070MmBvMBnTatKj5deEb59 
or for one track:
spotify:episode:0eX9Z7YBJSIenAyZRSTmiz

`
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 229, in run
    tracks = list(get_tracks_from_uri(uri))
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 224, in get_tracks_from_uri
    return self.load_link(uri)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 424, in load_link
    link = self.session.get_link(uri)
  File "/usr/local/lib/python2.7/dist-packages/spotify/session.py", line 376, in get_link
    return spotify.Link(self, uri=uri)
  File "/usr/local/lib/python2.7/dist-packages/spotify/link.py", line 73, in __init__
    'Failed to get link from Spotify URI: %r' % uri)
ValueError: Failed to get link from Spotify URI: 'spotify:show:070MmBvMBnTatKj5deEb59'
`

**Comment by tinuva** [comment]
This first needs to be implemented in the spotify web api. See https://github.com/spotify/web-api/issues/551
