### ISSUE TITLE
Error with Spotify Library Authentication

### ISSUE THREAD

**Issue by jeremy89632** [SolidHal/spotify-ripper#7]
Bumped into an error:

        
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/Users/USERNAME/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/USERNAME/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 229, in run
    tracks = list(get_tracks_from_uri(uri))
  File "/Users/USERNAME/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 224, in get_tracks_from_uri
    return self.load_link(uri)
  File "/Users/USERNAME/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 432, in load_link
    tracks = get_playlist_tracks(self.session.user.canonical_name, uri)
  File "/Users/USERNAME/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper/remove_all_from_playlist.py", line 34, in get_playlist_tracks
    token = util.prompt_for_user_token(username, scope)
  File "/Users/USERNAME/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotipy/util.py", line 47, in prompt_for_user_token
    raise spotipy.SpotifyException(550, -1, 'no credentials set')
SpotifyException: http status: 550, code:-1 - no credentials set

Any ideas?

**Comment by SolidHal** [comment]
Hm, I'm not sure if that's a bug in my code or a hard limit from the Web api. Based on it being the first 100, I would guess the latter but I'd assume theres a method to get the next 100. For now I would suggest splitting the playlist into <100 song playlists and just using a bash script to rip them back to back. I know it's not ideal.

**Comment by Minty123** [comment]
Hi there! You can find all the important information here:
https://developer.spotify.com/web-api/get-playlists-tracks/

It's just as you assumed, @SolidHal. The request with the endpoint `GET https://api.spotify.com/v1/users/{user_id}/playlists/{playlist_id}/tracks` returns at most 100 results. BUT you can just add the parameter `offset` to get the next 100 entries. Might not be too much work, so maybe I try to implement it once I have the time to do so.
